module.exports = function getBlockedUrlPatterns() {
  return [
    '*datadome*',
    '*doubleclick*',
    '*hotjar*',
    '*survicate*',
    '*scorecardresearch*'
    '*cloudflareinsights*'
    '*tremorhub*'
    '*2mdn*'
    '*quantserve*'
    '*adsrvr*'
    '*truste*'
    '*trustarc*'
    '*facebook*',
    '*quantcount*',
    '*pubmatic*',
    '*adlightning*',
    '*spotxchange*',
    '*branch.io*',
    '*connatix*',
    '*aaxads*',
    '*aaxdetect*'
    '*sentry*',
    '*aaxdetect*',
    '*app.link*',
    '*google*',
    '*brainly.com*',
    '*',
  ];
};
